class Gw7Style {
  final int number;
  final String name;
  final int tempo;

  const Gw7Style({
    required this.number,
    required this.name,
    required this.tempo,
  });
}

class Gw7StyleCategory {
  final String name;
  final List<Gw7Style> styles;

  const Gw7StyleCategory({required this.name, required this.styles});
}

/// The 110 preset Music Styles of the GW-7 (owner's manual p. 40).
const List<Gw7StyleCategory> gw7Styles = [
  Gw7StyleCategory(name: 'Rock', styles: [
    Gw7Style(number: 1, name: 'SteadyRk', tempo: 73),
    Gw7Style(number: 2, name: 'PowerRck', tempo: 132),
    Gw7Style(number: 3, name: 'ElecRock', tempo: 124),
    Gw7Style(number: 4, name: 'DynoRock', tempo: 76),
    Gw7Style(number: 5, name: 'ThumpRck', tempo: 104),
    Gw7Style(number: 6, name: 'USBallad', tempo: 88),
  ]),
  Gw7StyleCategory(name: 'Dance', styles: [
    Gw7Style(number: 7, name: 'FeverDnc', tempo: 113),
    Gw7Style(number: 8, name: '80sTekno', tempo: 134),
    Gw7Style(number: 9, name: 'EuroDnce', tempo: 138),
    Gw7Style(number: 10, name: 'IbizaDnc', tempo: 138),
    Gw7Style(number: 11, name: 'KeepOnDc', tempo: 140),
    Gw7Style(number: 12, name: '90sTekno', tempo: 140),
    Gw7Style(number: 13, name: 'HrdTekno', tempo: 140),
    Gw7Style(number: 14, name: '90sHouse', tempo: 132),
    Gw7Style(number: 15, name: 'ClubHous', tempo: 130),
    Gw7Style(number: 16, name: 'Hip\'nHop', tempo: 102),
    Gw7Style(number: 17, name: 'NowHipHp', tempo: 87),
    Gw7Style(number: 18, name: 'Cool Rap', tempo: 94),
    Gw7Style(number: 19, name: 'PianoRap', tempo: 94),
    Gw7Style(number: 20, name: '70sDance', tempo: 108),
    Gw7Style(number: 21, name: 'EasyHop', tempo: 88),
  ]),
  Gw7StyleCategory(name: '8Beat', styles: [
    Gw7Style(number: 22, name: 'PianoBal', tempo: 56),
    Gw7Style(number: 23, name: 'Soul Bal', tempo: 58),
    Gw7Style(number: 24, name: 'ClassBal', tempo: 62),
    Gw7Style(number: 25, name: 'SimpleBl', tempo: 80),
    Gw7Style(number: 26, name: 'AlClapBl', tempo: 80),
    Gw7Style(number: 27, name: 'LayBakBl', tempo: 83),
    Gw7Style(number: 28, name: 'PoppinBl', tempo: 92),
    Gw7Style(number: 29, name: 'UKLiteBl', tempo: 104),
    Gw7Style(number: 30, name: 'UpTempBl', tempo: 110),
    Gw7Style(number: 31, name: 'SmilePop', tempo: 118),
    Gw7Style(number: 32, name: 'German P', tempo: 120),
  ]),
  Gw7StyleCategory(name: '16Beat', styles: [
    Gw7Style(number: 33, name: 'Easy Pop', tempo: 64),
    Gw7Style(number: 34, name: 'Soul Pop', tempo: 75),
    Gw7Style(number: 35, name: 'NightPop', tempo: 78),
    Gw7Style(number: 36, name: 'Guitar P', tempo: 86),
    Gw7Style(number: 37, name: 'LatinPop', tempo: 92),
    Gw7Style(number: 38, name: 'LightPop', tempo: 94),
    Gw7Style(number: 39, name: 'FeelGood', tempo: 98),
    Gw7Style(number: 40, name: 'Groovy P', tempo: 100),
    Gw7Style(number: 41, name: 'SunnyPop', tempo: 104),
  ]),
  Gw7StyleCategory(name: 'Jazz', styles: [
    Gw7Style(number: 42, name: 'JzBallad', tempo: 70),
    Gw7Style(number: 43, name: 'BigBand', tempo: 144),
    Gw7Style(number: 44, name: 'JazzClub', tempo: 150),
    Gw7Style(number: 45, name: 'BgBndBld', tempo: 82),
    Gw7Style(number: 46, name: 'JazzWltz', tempo: 100),
  ]),
  Gw7StyleCategory(name: 'Latin', styles: [
    Gw7Style(number: 47, name: 'LuvBossa', tempo: 136),
    Gw7Style(number: 48, name: 'MidBossa', tempo: 150),
    Gw7Style(number: 49, name: 'UpBossa', tempo: 168),
    Gw7Style(number: 50, name: 'UpSamba', tempo: 103),
    Gw7Style(number: 51, name: 'Discsamb', tempo: 117),
    Gw7Style(number: 52, name: 'Salsa', tempo: 100),
    Gw7Style(number: 53, name: 'Merengue', tempo: 124),
    Gw7Style(number: 54, name: 'Bachata', tempo: 128),
    Gw7Style(number: 55, name: 'Jogetmly', tempo: 114),
    Gw7Style(number: 56, name: 'Guarach', tempo: 181),
  ]),
  Gw7StyleCategory(name: 'Traditional', styles: [
    Gw7Style(number: 57, name: 'Blues', tempo: 61),
    Gw7Style(number: 58, name: '70s R&B', tempo: 117),
    Gw7Style(number: 59, name: 'FunkSoul', tempo: 105),
    Gw7Style(number: 60, name: 'Reggae', tempo: 140),
    Gw7Style(number: 61, name: 'Country', tempo: 130),
    Gw7Style(number: 62, name: 'CntryPop', tempo: 105),
    Gw7Style(number: 63, name: 'Cajun', tempo: 114),
    Gw7Style(number: 64, name: 'Cool6_8', tempo: 64),
    Gw7Style(number: 65, name: 'Oldie6_8', tempo: 92),
    Gw7Style(number: 66, name: 'Schlager', tempo: 127),
    Gw7Style(number: 67, name: 'March4_4', tempo: 125),
    Gw7Style(number: 68, name: 'Polka', tempo: 130),
    Gw7Style(number: 69, name: 'PolkaPop', tempo: 127),
  ]),
  Gw7StyleCategory(name: 'Ballroom', styles: [
    Gw7Style(number: 70, name: '70sDisco', tempo: 126),
    Gw7Style(number: 71, name: 'BigSamba', tempo: 116),
    Gw7Style(number: 72, name: 'Rockin\'', tempo: 185),
    Gw7Style(number: 73, name: 'Boogie', tempo: 150),
    Gw7Style(number: 74, name: 'Twist', tempo: 162),
    Gw7Style(number: 75, name: 'EngWltz', tempo: 91),
    Gw7Style(number: 76, name: 'W\'Waltz', tempo: 180),
    Gw7Style(number: 77, name: 'SlWaltz', tempo: 90),
    Gw7Style(number: 78, name: 'Tango', tempo: 120),
    Gw7Style(number: 79, name: 'Musette', tempo: 175),
    Gw7Style(number: 80, name: 'Cha-Cha', tempo: 130),
    Gw7Style(number: 81, name: 'Mambo', tempo: 102),
    Gw7Style(number: 82, name: 'Beguine', tempo: 110),
    Gw7Style(number: 83, name: 'Rhumba', tempo: 100),
    Gw7Style(number: 84, name: 'Shuffle', tempo: 145),
    Gw7Style(number: 85, name: 'Foxtrot', tempo: 185),
    Gw7Style(number: 86, name: 'Charlest', tempo: 205),
    Gw7Style(number: 87, name: 'PasDoble', tempo: 122),
  ]),
  Gw7StyleCategory(name: 'World', styles: [
    Gw7Style(number: 88, name: 'Wehda-Kb', tempo: 120),
    Gw7Style(number: 89, name: 'WehdaKb2', tempo: 135),
    Gw7Style(number: 90, name: 'Masmoudi', tempo: 120),
    Gw7Style(number: 91, name: 'Dabkah-T', tempo: 113),
    Gw7Style(number: 92, name: 'Saidi', tempo: 110),
    Gw7Style(number: 93, name: 'Saidi-EG', tempo: 95),
    Gw7Style(number: 94, name: 'Progmks', tempo: 119),
    Gw7Style(number: 95, name: 'Disco-OR', tempo: 102),
    Gw7Style(number: 96, name: 'Raja Bha', tempo: 89),
    Gw7Style(number: 97, name: 'Dadra', tempo: 70),
    Gw7Style(number: 98, name: 'Kehrva A', tempo: 110),
    Gw7Style(number: 99, name: 'Bhangra', tempo: 109),
    Gw7Style(number: 100, name: 'Bangla', tempo: 110),
    Gw7Style(number: 101, name: 'Cmprsari', tempo: 132),
    Gw7Style(number: 102, name: 'Minang', tempo: 82),
    Gw7Style(number: 103, name: 'Popsunda', tempo: 98),
    Gw7Style(number: 104, name: 'Kromong', tempo: 128),
    Gw7Style(number: 105, name: 'Korean', tempo: 100),
    Gw7Style(number: 106, name: 'K_latin', tempo: 134),
    Gw7Style(number: 107, name: 'ChinaPop', tempo: 89),
    Gw7Style(number: 108, name: 'JiangNan', tempo: 72),
    Gw7Style(number: 109, name: 'ChnOpera', tempo: 120),
    Gw7Style(number: 110, name: 'JingJu', tempo: 136),
  ]),
];
